// react-frontend/src/components/Header/Header.tsx
import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import {
  AppBar,
  Toolbar,
  Typography,
  Button,
  Box,
  Chip,
  Menu,
  MenuItem,
  CircularProgress,
  Tooltip,
  Divider,
  IconButton
} from '@mui/material';
import {
  AccountBalanceWallet,
  KeyboardArrowDown,
  ContentCopy,
  Launch,
  Close
} from '@mui/icons-material';
import { useWallet } from '../../hooks/useWallet';
import { useTokenBalance } from '../../hooks/useTokenBalance';

export default function Header() {
  const navigate = useNavigate();
  const location = useLocation();
  
  const {
    isConnected,
    account,
    balance,
    chainId,
    isLoading,
    error,
    currentNetwork,
    supportedNetworks,
    connectWallet,
    disconnectWallet,
    switchNetwork,
    formatAddress,
    isSupportedNetwork,
    isMetaMaskInstalled
  } = useWallet();

  const { tokenBalances, getTokenBalance } = useTokenBalance();

  const [networkMenuAnchor, setNetworkMenuAnchor] = useState<null | HTMLElement>(null);
  const [walletMenuAnchor, setWalletMenuAnchor] = useState<null | HTMLElement>(null);

  const handleConnectWallet = async () => {
    try {
      await connectWallet();
    } catch (error) {
      console.error('Failed to connect wallet:', error);
    }
  };

  const handleNetworkSwitch = async (chainId: number) => {
    try {
      await switchNetwork(chainId);
      setNetworkMenuAnchor(null);
    } catch (error) {
      console.error('Failed to switch network:', error);
    }
  };

  const handleCopyAddress = () => {
    if (account) {
      navigator.clipboard.writeText(account);
      setWalletMenuAnchor(null);
    }
  };

  const openNetworkExplorer = () => {
    if (account && currentNetwork) {
      const explorerUrl = `${currentNetwork.blockExplorerUrl}/address/${account}`;
      window.open(explorerUrl, '_blank');
      setWalletMenuAnchor(null);
    }
  };

  const formatBalance = (balance: string): string => {
    const num = parseFloat(balance);
    return num.toFixed(4);
  };

  const getNetworkStatusColor = () => {
    if (!isConnected) return 'default';
    return isSupportedNetwork(chainId || 0) ? 'success' : 'error';
  };

  const getNetworkStatusText = () => {
    if (!isConnected) return 'Disconnected';
    return isSupportedNetwork(chainId || 0) ? 'Supported' : 'Unsupported';
  };

  const usdcBalance = getTokenBalance('USDC');

  const mainnetNetworks = supportedNetworks.filter(n => !n.isTestnet);
  const testnetNetworks = supportedNetworks.filter(n => n.isTestnet);

  const navigationItems = [
    { label: 'Home', path: '/' },
    { label: 'Properties', path: '/properties' },
    ...(isConnected ? [{ label: 'Dashboard', path: '/dashboard' }] : [])
  ];

  return (
    <AppBar position="static" sx={{ backgroundColor: 'background.paper', color: 'text.primary' }}>
      <Toolbar>
        <Typography 
          variant="h6" 
          component="div" 
          sx={{ fontWeight: 'bold', cursor: 'pointer', mr: 4 }}
          onClick={() => navigate('/')}
        >
          FracEstate
        </Typography>

        {/* Navigation Links */}
        <Box sx={{ display: { xs: 'none', md: 'flex' }, mr: 'auto' }}>
          {navigationItems.map((item) => (
            <Button
              key={item.path}
              color="inherit"
              onClick={() => navigate(item.path)}
              sx={{ 
                mx: 1,
                fontWeight: location.pathname === item.path ? 600 : 400,
                color: location.pathname === item.path ? 'primary.main' : 'inherit'
              }}
            >
              {item.label}
            </Button>
          ))}
        </Box>

        {/* Network Status */}
        {isConnected && (
          <Box sx={{ display: 'flex', alignItems: 'center', mr: 2 }}>
            <Button
              variant="outlined"
              size="small"
              onClick={(e) => setNetworkMenuAnchor(e.currentTarget)}
              endIcon={<KeyboardArrowDown />}
              sx={{ mr: 1 }}
            >
              {currentNetwork?.displayName || 'Unknown Network'}
            </Button>
            <Chip
              label={getNetworkStatusText()}
              color={getNetworkStatusColor()}
              size="small"
            />
          </Box>
        )}

        {/* Balance Display */}
        {isConnected && (
          <Box sx={{ display: 'flex', alignItems: 'center', mr: 2 }}>
            <Chip
              label={`${formatBalance(balance)} ${currentNetwork?.symbol || 'ETH'}`}
              variant="outlined"
              size="small"
              sx={{ mr: 1 }}
            />
            {usdcBalance && (
              <Chip
                label={`${usdcBalance.formatted} USDC`}
                variant="outlined"
                size="small"
              />
            )}
          </Box>
        )}

        {/* Wallet Connection */}
        {!isMetaMaskInstalled ? (
          <Button
            variant="contained"
            color="primary"
            onClick={() => window.open('https://metamask.io/', '_blank')}
          >
            Install MetaMask
          </Button>
        ) : !isConnected ? (
          <Button
            variant="contained"
            color="primary"
            onClick={handleConnectWallet}
            disabled={isLoading}
            startIcon={isLoading ? <CircularProgress size={16} /> : <AccountBalanceWallet />}
          >
            {isLoading ? 'Connecting...' : 'Connect Wallet'}
          </Button>
        ) : (
          <Button
            variant="outlined"
            onClick={(e) => setWalletMenuAnchor(e.currentTarget)}
            startIcon={<AccountBalanceWallet />}
            endIcon={<KeyboardArrowDown />}
          >
            {formatAddress(account || '')}
          </Button>
        )}

        {/* Network Selection Menu */}
        <Menu
          anchorEl={networkMenuAnchor}
          open={Boolean(networkMenuAnchor)}
          onClose={() => setNetworkMenuAnchor(null)}
          PaperProps={{
            sx: { minWidth: 250 }
          }}
        >
          <Typography variant="subtitle2" sx={{ px: 2, py: 1, fontWeight: 'bold' }}>
            Mainnet Networks
          </Typography>
          {mainnetNetworks.map((network) => (
            <MenuItem
              key={network.chainId}
              onClick={() => handleNetworkSwitch(network.chainId)}
              selected={network.chainId === chainId}
            >
              <Box sx={{ display: 'flex', justifyContent: 'space-between', width: '100%' }}>
                <Typography>{network.displayName}</Typography>
                <Typography variant="body2" color="text.secondary">
                  {network.symbol}
                </Typography>
              </Box>
            </MenuItem>
          ))}
          
          {testnetNetworks.length > 0 && (
            <>
              <Divider />
              <Typography variant="subtitle2" sx={{ px: 2, py: 1, fontWeight: 'bold' }}>
                Testnet Networks
              </Typography>
              {testnetNetworks.map((network) => (
                <MenuItem
                  key={network.chainId}
                  onClick={() => handleNetworkSwitch(network.chainId)}
                  selected={network.chainId === chainId}
                >
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', width: '100%' }}>
                    <Typography>{network.displayName}</Typography>
                    <Typography variant="body2" color="text.secondary">
                      {network.symbol}
                    </Typography>
                  </Box>
                </MenuItem>
              ))}
            </>
          )}
        </Menu>

        {/* Wallet Menu */}
        <Menu
          anchorEl={walletMenuAnchor}
          open={Boolean(walletMenuAnchor)}
          onClose={() => setWalletMenuAnchor(null)}
          PaperProps={{
            sx: { minWidth: 300 }
          }}
        >
          <Box sx={{ p: 2 }}>
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Connected Account
            </Typography>
            <Typography variant="body2" sx={{ fontFamily: 'monospace', mb: 1 }}>
              {account}
            </Typography>
            <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
              <Tooltip title="Copy Address">
                <IconButton size="small" onClick={handleCopyAddress}>
                  <ContentCopy fontSize="small" />
                </IconButton>
              </Tooltip>
              <Tooltip title="View on Explorer">
                <IconButton size="small" onClick={openNetworkExplorer}>
                  <Launch fontSize="small" />
                </IconButton>
              </Tooltip>
            </Box>
            
            <Typography variant="subtitle2" color="text.secondary" gutterBottom>
              Balances
            </Typography>
            <Box sx={{ mb: 2 }}>
              <Typography variant="body2">
                {formatBalance(balance)} {currentNetwork?.symbol || 'ETH'}
              </Typography>
              {tokenBalances.map((token) => (
                <Typography key={token.symbol} variant="body2">
                  {token.formatted} {token.symbol}
                </Typography>
              ))}
            </Box>
          </Box>
          
          <Divider />
          
          <MenuItem onClick={disconnectWallet}>
            <Close sx={{ mr: 1 }} />
            Disconnect Wallet
          </MenuItem>
        </Menu>

        {/* Error Display */}
        {error && (
          <Chip
            label={error}
            color="error"
            size="small"
            sx={{ ml: 1 }}
          />
        )}
      </Toolbar>
    </AppBar>
  );
}

// frontend/src/app/components/header/header.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatChipsModule } from '@angular/material/chips';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTooltipModule } from '@angular/material/tooltip';
import { MatDividerModule } from '@angular/material/divider';
import { Subject, takeUntil, combineLatest } from 'rxjs';

import { WalletService, WalletState } from '../../services/wallet.service';
import { NetworkService, Network } from '../../services/network.service';
import { Web3Service, TokenBalance } from '../../services/web3.service';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    MatChipsModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatDividerModule
  ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  walletState: WalletState | null = null;
  currentNetwork: Network | null = null;
  supportedNetworks: Network[] = [];
  tokenBalances: TokenBalance[] = [];
  
  isConnecting = false;
  showNetworkMenu = false;

  constructor(
    private walletService: WalletService,
    private networkService: NetworkService,
    private web3Service: Web3Service
  ) {}

  ngOnInit(): void {
    this.subscribeToServices();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private subscribeToServices(): void {
    // Subscribe to wallet state
    this.walletService.walletState$
      .pipe(takeUntil(this.destroy$))
      .subscribe(state => {
        this.walletState = state;
        this.isConnecting = state.isLoading;
      });

    // Subscribe to network changes
    this.networkService.currentNetwork$
      .pipe(takeUntil(this.destroy$))
      .subscribe(network => {
        this.currentNetwork = network;
      });

    // Subscribe to supported networks
    this.networkService.supportedNetworks$
      .pipe(takeUntil(this.destroy$))
      .subscribe(networks => {
        this.supportedNetworks = networks;
      });

    // Subscribe to token balances
    this.web3Service.tokenBalances$
      .pipe(takeUntil(this.destroy$))
      .subscribe(balances => {
        this.tokenBalances = balances;
      });
  }

  async connectWallet(): Promise<void> {
    if (this.isConnecting) return;

    try {
      await this.walletService.connect();
    } catch (error: any) {
      console.error('Failed to connect wallet:', error);
      // Error handling could be enhanced with toast notifications
    }
  }

  disconnectWallet(): void {
    this.walletService.disconnect();
  }

  async switchNetwork(chainId: number): Promise<void> {
    if (!this.walletState?.isConnected || this.isConnecting) return;

    try {
      await this.networkService.switchNetwork(chainId);
    } catch (error: any) {
      console.error('Failed to switch network:', error);
      // Error handling could be enhanced with toast notifications
    }
  }

  get isWalletConnected(): boolean {
    return this.walletState?.isConnected || false;
  }

  get formattedAddress(): string {
    if (!this.walletState?.account) return '';
    return this.walletService.formatAddress(this.walletState.account);
  }

  get formattedBalance(): string {
    if (!this.walletState?.balance) return '0.00';
    const balance = parseFloat(this.walletState.balance);
    return balance.toFixed(4);
  }

  get currentNetworkSymbol(): string {
    return this.currentNetwork?.symbol || 'ETH';
  }

  get currentNetworkName(): string {
    return this.currentNetwork?.displayName || 'Unknown Network';
  }

  get isNetworkSupported(): boolean {
    if (!this.walletState?.chainId) return false;
    return this.networkService.isNetworkSupported(this.walletState.chainId);
  }

  get networkStatusClass(): string {
    if (!this.isWalletConnected) return 'disconnected';
    return this.isNetworkSupported ? 'supported' : 'unsupported';
  }

  get usdcBalance(): string {
    const usdcToken = this.tokenBalances.find(token => token.symbol === 'USDC');
    return usdcToken ? usdcToken.formatted : '0.00';
  }

  openNetworkExplorer(): void {
    if (!this.walletState?.account || !this.currentNetwork) return;
    
    const explorerUrl = this.networkService.getNetworkExplorerUrl(undefined, this.walletState.account);
    if (explorerUrl) {
      window.open(explorerUrl, '_blank');
    }
  }

  copyAddress(): void {
    if (!this.walletState?.account) return;
    
    navigator.clipboard.writeText(this.walletState.account).then(() => {
      // Could show a toast notification here
      console.log('Address copied to clipboard');
    });
  }

  get mainnetNetworks(): Network[] {
    return this.supportedNetworks.filter(network => !network.isTestnet);
  }

  get testnetNetworks(): Network[] {
    return this.supportedNetworks.filter(network => network.isTestnet);
  }

  get mainnetNetworkNames(): string {
    return this.mainnetNetworks.map(n => n.displayName).join(', ');
  }

  // Helper method for debugging - can be removed in production
  get walletStateForDebug(): any {
    return {
      isConnected: this.walletState?.isConnected,
      account: this.walletState?.account,
      chainId: this.walletState?.chainId,
      balance: this.walletState?.balance,
      isLoading: this.walletState?.isLoading,
      error: this.walletState?.error
    };
  }
}

<mat-toolbar class="header-toolbar glass-card">
  <div class="toolbar-content">
    <!-- Logo & Brand -->
    <div class="brand-section fade-in" [routerLink]="['/']">
      <div class="logo-container">
        <div class="logo-icon">🏛️</div>
        <h1 class="brand-title crypto-title">FracEstate</h1>
      </div>
      <div class="tagline">Blockchain Real Estate</div>
    </div>

    <!-- Navigation Menu -->
    <nav class="nav-menu">
      <a mat-button 
         routerLink="/properties" 
         routerLinkActive="active-link"
         class="nav-link">
        <mat-icon>home</mat-icon>
        Properties
      </a>
    </nav>

    <div class="spacer"></div>

    <!-- Wallet & Network Section -->
    <div class="wallet-section slide-up">
      
      <!-- Network Selector -->
      @if (isWalletConnected) {
        <div class="network-selector" [ngClass]="networkStatusClass">
          <button mat-button 
                  [matMenuTriggerFor]="networkMenu" 
                  class="network-button glass-button"
                  [matTooltip]="isNetworkSupported ? 'Switch Network' : 'Unsupported Network'">
            <div class="network-info">
              <div class="network-indicator" [ngClass]="networkStatusClass"></div>
              <span class="network-name">{{ currentNetworkName }}</span>
              <mat-icon>expand_more</mat-icon>
            </div>
          </button>
          
          <mat-menu #networkMenu="matMenu" class="network-menu">
            <div class="network-menu-header">
              <h3>Select Network</h3>
            </div>
            
            <div class="network-group">
              <div class="network-group-label">Mainnet</div>
              @for (network of mainnetNetworks; track network.chainId) {
                <button mat-menu-item 
                        (click)="switchNetwork(network.chainId)"
                        [disabled]="currentNetwork?.chainId === network.chainId"
                        class="network-menu-item">
                  <div class="network-menu-content">
                    <div class="network-icon">🌐</div>
                    <div class="network-details">
                      <div class="network-name">{{ network.displayName }}</div>
                      <div class="network-symbol">{{ network.symbol }}</div>
                    </div>
                    @if (currentNetwork?.chainId === network.chainId) {
                      <mat-icon class="current-network-check">check</mat-icon>
                    }
                  </div>
                </button>
              }
            </div>

            <div class="network-group">
              <div class="network-group-label">Testnet</div>
              @for (network of testnetNetworks; track network.chainId) {
                <button mat-menu-item 
                        (click)="switchNetwork(network.chainId)"
                        [disabled]="currentNetwork?.chainId === network.chainId"
                        class="network-menu-item testnet">
                  <div class="network-menu-content">
                    <div class="network-icon">🧪</div>
                    <div class="network-details">
                      <div class="network-name">{{ network.displayName }}</div>
                      <div class="network-symbol">{{ network.symbol }}</div>
                    </div>
                    @if (currentNetwork?.chainId === network.chainId) {
                      <mat-icon class="current-network-check">check</mat-icon>
                    }
                  </div>
                </button>
              }
            </div>
          </mat-menu>
        </div>
      }

      <!-- Balance Display -->
      @if (isWalletConnected) {
        <div class="balance-display glass-card">
          <div class="balance-item">
            <div class="balance-label">{{ currentNetworkSymbol }}</div>
            <div class="balance-value">{{ formattedBalance }}</div>
          </div>
          <div class="balance-separator"></div>
          <div class="balance-item">
            <div class="balance-label">USDC</div>
            <div class="balance-value">{{ usdcBalance }}</div>
          </div>
        </div>
      }

      <!-- Wallet Connection -->
      <div class="wallet-connection">
        @if (!isWalletConnected) {
          <!-- Connect Wallet Button -->
          <button mat-raised-button 
                  color="primary" 
                  (click)="connectWallet()" 
                  [disabled]="isConnecting"
                  class="connect-button glass-button">
            @if (isConnecting) {
              <mat-spinner diameter="20" class="spinner"></mat-spinner>
              <span>Connecting...</span>
            } @else {
              <mat-icon>account_balance_wallet</mat-icon>
              <span>Connect Wallet</span>
            }
          </button>
        } @else {
          <!-- Connected Wallet Info -->
          <div class="wallet-info glass-button" [matMenuTriggerFor]="walletMenu">
            <div class="wallet-avatar">
              <div class="avatar-circle">
                {{ formattedAddress.substring(0, 2).toUpperCase() }}
              </div>
            </div>
            <div class="wallet-details">
              <div class="wallet-address">{{ formattedAddress }}</div>
              <div class="wallet-status" [ngClass]="networkStatusClass">
                @if (isNetworkSupported) {
                  <span>Connected</span>
                } @else {
                  <span>Wrong Network</span>
                }
              </div>
            </div>
            <mat-icon class="dropdown-icon">expand_more</mat-icon>
          </div>

          <mat-menu #walletMenu="matMenu" class="wallet-menu">
            <div class="wallet-menu-header">
              <div class="wallet-address-full">{{ walletState?.account }}</div>
            </div>
            
            <button mat-menu-item (click)="copyAddress()" class="wallet-menu-item">
              <mat-icon>content_copy</mat-icon>
              <span>Copy Address</span>
            </button>
            
            <button mat-menu-item (click)="openNetworkExplorer()" class="wallet-menu-item">
              <mat-icon>open_in_new</mat-icon>
              <span>View on Explorer</span>
            </button>
            
            <mat-divider></mat-divider>
            
            <button mat-menu-item (click)="disconnectWallet()" class="wallet-menu-item disconnect">
              <mat-icon>power_settings_new</mat-icon>
              <span>Disconnect</span>
            </button>
          </mat-menu>
        }
      </div>
    </div>
  </div>

  <!-- Error Banner -->
  @if (walletState?.error) {
    <div class="error-banner slide-up">
      <mat-icon class="error-icon">error</mat-icon>
      <span class="error-message">{{ walletState?.error }}</span>
      <button mat-icon-button (click)="walletState && (walletState.error = null)" class="close-error">
        <mat-icon>close</mat-icon>
      </button>
    </div>
  }

  <!-- Unsupported Network Warning -->
  @if (isWalletConnected && !isNetworkSupported) {
    <div class="warning-banner slide-up">
      <mat-icon class="warning-icon">warning</mat-icon>
      <span class="warning-message">
        Please switch to a supported network: {{ mainnetNetworkNames }}
      </span>
      <button mat-raised-button 
              color="accent" 
              (click)="switchNetwork(1)"
              class="switch-network-btn">
        Switch to Ethereum
      </button>
    </div>
  }
</mat-toolbar>
