// frontend/src/app/components/property-list/property-list.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatGridListModule } from '@angular/material/grid-list';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatChipsModule } from '@angular/material/chips';
import { MatSliderModule } from '@angular/material/slider';
import { MatCardModule } from '@angular/material/card';
import { PropertyCardComponent } from '../property-card/property-card.component';
import { PropertyDetails, ContractService } from '../../services/contract.service';
import { Subject, BehaviorSubject, combineLatest } from 'rxjs';
import { takeUntil, debounceTime, distinctUntilChanged, startWith, map } from 'rxjs/operators';

export interface PropertyFilters {
  searchTerm: string;
  priceRange: { min: number; max: number };
  statusFilter: string;
  sortBy: 'price' | 'funding' | 'shares' | 'newest';
  sortOrder: 'asc' | 'desc';
}

@Component({
  selector: 'app-property-list',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatGridListModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatChipsModule,
    MatSliderModule,
    MatCardModule,
    PropertyCardComponent
  ],
  template: `
    <div class="property-list-container">
      <!-- Header -->
      <div class="list-header">
        <h2>Available Properties</h2>
        <div class="property-count">
          {{ filteredProperties.length }} of {{ allProperties.length }} properties
        </div>
      </div>

      <!-- Filters Section -->
      <mat-card class="filters-card">
        <mat-card-content>
          <div class="filters-container">
            <!-- Search -->
            <mat-form-field class="search-field" appearance="outline">
              <mat-label>Search properties</mat-label>
              <input matInput
                     [(ngModel)]="filters.searchTerm"
                     (input)="onFiltersChange()"
                     placeholder="Search by name, location, or description">
              <mat-icon matSuffix>search</mat-icon>
            </mat-form-field>

            <!-- Status Filter -->
            <mat-form-field appearance="outline">
              <mat-label>Status</mat-label>
              <mat-select [(value)]="filters.statusFilter" (selectionChange)="onFiltersChange()">
                <mat-option value="">All Status</mat-option>
                <mat-option value="0">Available for Investment</mat-option>
                <mat-option value="1">Under Inspection</mat-option>
                <mat-option value="2">Pending Approval</mat-option>
                <mat-option value="3">Funding Complete</mat-option>
                <mat-option value="4">Completed</mat-option>
                <mat-option value="5">Cancelled</mat-option>
              </mat-select>
            </mat-form-field>

            <!-- Sort Options -->
            <mat-form-field appearance="outline">
              <mat-label>Sort by</mat-label>
              <mat-select [(value)]="filters.sortBy" (selectionChange)="onFiltersChange()">
                <mat-option value="newest">Newest First</mat-option>
                <mat-option value="price">Price</mat-option>
                <mat-option value="funding">Funding Progress</mat-option>
                <mat-option value="shares">Available Shares</mat-option>
              </mat-select>
            </mat-form-field>

            <!-- Sort Order -->
            <mat-form-field appearance="outline">
              <mat-label>Order</mat-label>
              <mat-select [(value)]="filters.sortOrder" (selectionChange)="onFiltersChange()">
                <mat-option value="asc">Ascending</mat-option>
                <mat-option value="desc">Descending</mat-option>
              </mat-select>
            </mat-form-field>

            <!-- Clear Filters -->
            <button mat-button 
                    (click)="clearFilters()" 
                    class="clear-filters-btn">
              <mat-icon>clear</mat-icon>
              Clear Filters
            </button>
          </div>

          <!-- Price Range Slider -->
          <div class="price-range-container">
            <label>Price Range: {{formatCurrency(filters.priceRange.min)}} - {{formatCurrency(filters.priceRange.max)}}</label>
            <mat-slider 
              class="price-slider"
              [min]="priceRange.min"
              [max]="priceRange.max"
              [step]="10000">
              <input matSliderStartThumb 
                     [(ngModel)]="filters.priceRange.min" 
                     (input)="onPriceRangeChange()">
              <input matSliderEndThumb 
                     [(ngModel)]="filters.priceRange.max" 
                     (input)="onPriceRangeChange()">
            </mat-slider>
          </div>
        </mat-card-content>
      </mat-card>

      <!-- Active Filters Display -->
      <div class="active-filters" *ngIf="hasActiveFilters()">
        <mat-chip-listbox class="filter-chips">
          <mat-chip-option *ngIf="filters.searchTerm" 
                          (removed)="removeFilter('search')"
                          removable>
            Search: {{ filters.searchTerm }}
            <mat-icon matChipRemove>cancel</mat-icon>
          </mat-chip-option>
          
          <mat-chip-option *ngIf="filters.statusFilter" 
                          (removed)="removeFilter('status')"
                          removable>
            Status: {{ getStatusLabel(filters.statusFilter) }}
            <mat-icon matChipRemove>cancel</mat-icon>
          </mat-chip-option>
          
          <mat-chip-option *ngIf="isPriceRangeFiltered()" 
                          (removed)="removeFilter('price')"
                          removable>
            Price: {{formatCurrency(filters.priceRange.min)}} - {{formatCurrency(filters.priceRange.max)}}
            <mat-icon matChipRemove>cancel</mat-icon>
          </mat-chip-option>
        </mat-chip-listbox>
      </div>

      <!-- Loading State -->
      <div class="loading-container" *ngIf="isLoading">
        <mat-progress-spinner diameter="60" mode="indeterminate"></mat-progress-spinner>
        <p>Loading properties...</p>
      </div>

      <!-- Empty State -->
      <div class="empty-state" *ngIf="!isLoading && filteredProperties.length === 0 && allProperties.length === 0">
        <mat-icon class="empty-icon">home</mat-icon>
        <h3>No Properties Available</h3>
        <p>There are currently no properties available for investment.</p>
        <button mat-raised-button color="primary" (click)="refreshProperties()">
          <mat-icon>refresh</mat-icon>
          Refresh
        </button>
      </div>

      <!-- No Results State -->
      <div class="empty-state" *ngIf="!isLoading && filteredProperties.length === 0 && allProperties.length > 0">
        <mat-icon class="empty-icon">search_off</mat-icon>
        <h3>No Properties Found</h3>
        <p>No properties match your current filters. Try adjusting your search criteria.</p>
        <button mat-button color="primary" (click)="clearFilters()">
          <mat-icon>clear</mat-icon>
          Clear All Filters
        </button>
      </div>

      <!-- Properties Grid -->
      <div class="properties-grid" *ngIf="!isLoading && filteredProperties.length > 0">
        <app-property-card
          *ngFor="let property of filteredProperties; trackBy: trackByProperty"
          [property]="property"
          [escrowAddress]="getPropertyAddress(property)">
        </app-property-card>
      </div>

      <!-- Load More Button -->
      <div class="load-more-container" *ngIf="canLoadMore()">
        <button mat-raised-button 
                color="primary" 
                (click)="loadMoreProperties()"
                [disabled]="isLoadingMore">
          <mat-icon *ngIf="!isLoadingMore">expand_more</mat-icon>
          <mat-progress-spinner *ngIf="isLoadingMore" diameter="20"></mat-progress-spinner>
          {{ isLoadingMore ? 'Loading...' : 'Load More Properties' }}
        </button>
      </div>
    </div>
  `,
  styleUrls: ['./property-list.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PropertyListComponent implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();
  private filtersSubject = new BehaviorSubject<PropertyFilters>(this.getDefaultFilters());

  allProperties: PropertyDetails[] = [];
  filteredProperties: PropertyDetails[] = [];
  isLoading = false;
  isLoadingMore = false;
  currentPage = 1;
  pageSize = 12;

  filters: PropertyFilters = this.getDefaultFilters();
  priceRange = { min: 0, max: 2000000 };

  // Mock property addresses for now - in real app, these would come from your contract registry
  private propertyAddresses = [
    '0x1234567890123456789012345678901234567890',
    '0x2345678901234567890123456789012345678901',
    '0x3456789012345678901234567890123456789012'
  ];

  constructor(
    private contractService: ContractService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    this.setupFilterSubscription();
    this.loadProperties();
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private setupFilterSubscription() {
    this.filtersSubject.pipe(
      debounceTime(300),
      distinctUntilChanged((a, b) => JSON.stringify(a) === JSON.stringify(b)),
      takeUntil(this.destroy$)
    ).subscribe(filters => {
      this.applyFilters();
    });
  }

  async loadProperties() {
    this.isLoading = true;
    this.cdr.markForCheck();

    try {
      // Load properties from contract addresses
      const propertyPromises = this.propertyAddresses.map(address => 
        this.contractService.getPropertyDetails(address)
      );

      const properties = await Promise.all(propertyPromises);
      this.allProperties = properties.filter((p): p is PropertyDetails => p !== null);
      
      this.updatePriceRange();
      this.applyFilters();
      
    } catch (error) {
      console.error('Failed to load properties:', error);
      this.allProperties = [];
      this.filteredProperties = [];
    } finally {
      this.isLoading = false;
      this.cdr.markForCheck();
    }
  }

  private updatePriceRange() {
    if (this.allProperties.length === 0) return;

    const prices = this.allProperties.map(p => Number(p.config.purchasePrice) / 1e6);
    this.priceRange = {
      min: Math.floor(Math.min(...prices) / 10000) * 10000,
      max: Math.ceil(Math.max(...prices) / 10000) * 10000
    };

    this.filters.priceRange = { ...this.priceRange };
  }

  private applyFilters() {
    let filtered = [...this.allProperties];

    // Apply search filter
    if (this.filters.searchTerm) {
      const searchTerm = this.filters.searchTerm.toLowerCase();
      filtered = filtered.filter(property => {
        // In a real app, you'd search through metadata
        return property.config.nftID.toString().includes(searchTerm) ||
               property.config.seller.toLowerCase().includes(searchTerm);
      });
    }

    // Apply status filter
    if (this.filters.statusFilter) {
      const statusId = parseInt(this.filters.statusFilter);
      filtered = filtered.filter(property => property.currentPhase.id === statusId);
    }

    // Apply price range filter
    filtered = filtered.filter(property => {
      const price = Number(property.config.purchasePrice) / 1e6;
      return price >= this.filters.priceRange.min && price <= this.filters.priceRange.max;
    });

    // Apply sorting
    filtered = this.sortProperties(filtered);

    // Apply pagination
    const startIndex = (this.currentPage - 1) * this.pageSize;
    this.filteredProperties = filtered.slice(0, startIndex + this.pageSize);

    this.cdr.markForCheck();
  }

  private sortProperties(properties: PropertyDetails[]): PropertyDetails[] {
    const { sortBy, sortOrder } = this.filters;

    return properties.sort((a, b) => {
      let comparison = 0;

      switch (sortBy) {
        case 'price':
          comparison = Number(a.config.purchasePrice) - Number(b.config.purchasePrice);
          break;
        case 'funding':
          const aFunding = Number(a.totalEarnestDeposited) / Number(a.config.escrowAmount) || 0;
          const bFunding = Number(b.totalEarnestDeposited) / Number(b.config.escrowAmount) || 0;
          comparison = aFunding - bFunding;
          break;
        case 'shares':
          comparison = a.availableShares - b.availableShares;
          break;
        case 'newest':
        default:
          comparison = Number(b.currentPhase.timestamp) - Number(a.currentPhase.timestamp);
          break;
      }

      return sortOrder === 'desc' ? -comparison : comparison;
    });
  }

  onFiltersChange() {
    this.filtersSubject.next({ ...this.filters });
  }

  onPriceRangeChange() {
    // Debounce the price range changes
    setTimeout(() => {
      this.filtersSubject.next({ ...this.filters });
    }, 300);
  }

  clearFilters() {
    this.filters = this.getDefaultFilters();
    this.filters.priceRange = { ...this.priceRange };
    this.currentPage = 1;
    this.onFiltersChange();
  }

  removeFilter(filterType: string) {
    switch (filterType) {
      case 'search':
        this.filters.searchTerm = '';
        break;
      case 'status':
        this.filters.statusFilter = '';
        break;
      case 'price':
        this.filters.priceRange = { ...this.priceRange };
        break;
    }
    this.onFiltersChange();
  }

  hasActiveFilters(): boolean {
    return this.filters.searchTerm !== '' || 
           this.filters.statusFilter !== '' || 
           this.isPriceRangeFiltered();
  }

  isPriceRangeFiltered(): boolean {
    return this.filters.priceRange.min !== this.priceRange.min || 
           this.filters.priceRange.max !== this.priceRange.max;
  }

  getStatusLabel(statusId: string): string {
    const labels: Record<string, string> = {
      '0': 'Available for Investment',
      '1': 'Under Inspection',
      '2': 'Pending Approval',
      '3': 'Funding Complete',
      '4': 'Completed',
      '5': 'Cancelled'
    };
    return labels[statusId] || 'Unknown';
  }

  canLoadMore(): boolean {
    const totalFiltered = this.allProperties.filter(p => this.passesFilters(p)).length;
    return this.filteredProperties.length < totalFiltered && !this.isLoading;
  }

  private passesFilters(property: PropertyDetails): boolean {
    // Simplified filter check - implement full logic as needed
    return true;
  }

  loadMoreProperties() {
    this.isLoadingMore = true;
    this.currentPage++;
    
    // Simulate loading delay
    setTimeout(() => {
      this.applyFilters();
      this.isLoadingMore = false;
      this.cdr.markForCheck();
    }, 1000);
  }

  refreshProperties() {
    this.currentPage = 1;
    this.loadProperties();
  }

  trackByProperty(index: number, property: PropertyDetails): string {
    return `${property.config.nftAddress}-${property.config.nftID}`;
  }

  getPropertyAddress(property: PropertyDetails): string {
    // In a real app, you'd have a mapping from property to escrow address
    const index = this.allProperties.indexOf(property);
    return this.propertyAddresses[index] || '';
  }

  private getDefaultFilters(): PropertyFilters {
    return {
      searchTerm: '',
      priceRange: { min: 0, max: 2000000 },
      statusFilter: '',
      sortBy: 'newest',
      sortOrder: 'desc'
    };
  }

  formatCurrency(value: number): string {
    return '$' + value.toLocaleString('en-US');
  }
}

// react-frontend/src/components/PropertyList/PropertyList.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
  Box,
  Typography,
  Card,
  CardContent,
  TextField,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Button,
  Grid,
  Chip,
  CircularProgress,
  Slider,
  Divider,
  IconButton
} from '@mui/material';
import {
  Search,
  Clear,
  Refresh,
  Home,
  SearchOff
} from '@mui/icons-material';
import { useContracts } from '../../hooks/useContracts';
import { PropertyDetails } from '../../types/web3';
import PropertyCard from '../PropertyCard/PropertyCard';
import { ethers } from 'ethers';

interface PropertyFilters {
  searchTerm: string;
  priceRange: { min: number; max: number };
  statusFilter: string;
  sortBy: 'price' | 'funding' | 'shares' | 'newest';
  sortOrder: 'asc' | 'desc';
}

export default function PropertyList() {
  const { getPropertyDetails } = useContracts();
  
  const [allProperties, setAllProperties] = useState<Array<{ property: PropertyDetails; address: string }>>([]);
  const [filteredProperties, setFilteredProperties] = useState<Array<{ property: PropertyDetails; address: string }>>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingMore, setIsLoadingMore] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [filters, setFilters] = useState<PropertyFilters>({
    searchTerm: '',
    priceRange: { min: 0, max: 2000000 },
    statusFilter: '',
    sortBy: 'newest',
    sortOrder: 'desc'
  });

  const pageSize = 12;
  const [priceRange] = useState({ min: 0, max: 2000000 });

  // Mock property addresses - in a real app, these would come from your contract registry
  const propertyAddresses = [
    '0x1234567890123456789012345678901234567890',
    '0x2345678901234567890123456789012345678901',
    '0x3456789012345678901234567890123456789012',
    '0x4567890123456789012345678901234567890123',
    '0x5678901234567890123456789012345678901234'
  ];

  const loadProperties = useCallback(async () => {
    setIsLoading(true);
    
    try {
      const propertyPromises = propertyAddresses.map(async (address) => {
        const property = await getPropertyDetails(address);
        return property ? { property, address } : null;
      });

      const results = await Promise.all(propertyPromises);
      const validProperties = results.filter((p): p is { property: PropertyDetails; address: string } => p !== null);
      
      setAllProperties(validProperties);
    } catch (error) {
      console.error('Failed to load properties:', error);
      setAllProperties([]);
    } finally {
      setIsLoading(false);
    }
  }, [getPropertyDetails]);

  useEffect(() => {
    loadProperties();
  }, [loadProperties]);

  const applyFilters = useCallback(() => {
    let filtered = [...allProperties];

    // Apply search filter
    if (filters.searchTerm) {
      const searchTerm = filters.searchTerm.toLowerCase();
      filtered = filtered.filter(({ property }) => {
        return (
          property.config.nftID.toString().includes(searchTerm) ||
          property.config.seller.toLowerCase().includes(searchTerm) ||
          property.currentPhase.name.toLowerCase().includes(searchTerm)
        );
      });
    }

    // Apply status filter
    if (filters.statusFilter) {
      const statusId = parseInt(filters.statusFilter);
      filtered = filtered.filter(({ property }) => property.currentPhase.id === statusId);
    }

    // Apply price range filter
    filtered = filtered.filter(({ property }) => {
      const price = Number(ethers.formatUnits(property.config.purchasePrice, 6));
      return price >= filters.priceRange.min && price <= filters.priceRange.max;
    });

    // Apply sorting
    filtered = filtered.sort(({ property: a }, { property: b }) => {
      let comparison = 0;

      switch (filters.sortBy) {
        case 'price':
          comparison = Number(a.config.purchasePrice) - Number(b.config.purchasePrice);
          break;
        case 'funding':
          const aFunding = Number(a.totalEarnestDeposited) / Number(a.config.escrowAmount) || 0;
          const bFunding = Number(b.totalEarnestDeposited) / Number(b.config.escrowAmount) || 0;
          comparison = aFunding - bFunding;
          break;
        case 'shares':
          comparison = a.availableShares - b.availableShares;
          break;
        case 'newest':
        default:
          comparison = Number(b.currentPhase.timestamp) - Number(a.currentPhase.timestamp);
          break;
      }

      return filters.sortOrder === 'desc' ? -comparison : comparison;
    });

    // Apply pagination
    const startIndex = (currentPage - 1) * pageSize;
    const paginated = filtered.slice(0, startIndex + pageSize);
    
    setFilteredProperties(paginated);
  }, [allProperties, filters, currentPage]);

  useEffect(() => {
    applyFilters();
  }, [applyFilters]);

  const handleFilterChange = (key: keyof PropertyFilters, value: any) => {
    setFilters(prev => ({ ...prev, [key]: value }));
    setCurrentPage(1);
  };

  const clearFilters = () => {
    setFilters({
      searchTerm: '',
      priceRange: { ...priceRange },
      statusFilter: '',
      sortBy: 'newest',
      sortOrder: 'desc'
    });
    setCurrentPage(1);
  };

  const removeFilter = (filterType: string) => {
    switch (filterType) {
      case 'search':
        handleFilterChange('searchTerm', '');
        break;
      case 'status':
        handleFilterChange('statusFilter', '');
        break;
      case 'price':
        handleFilterChange('priceRange', { ...priceRange });
        break;
    }
  };

  const hasActiveFilters = useMemo(() => {
    return (
      filters.searchTerm !== '' || 
      filters.statusFilter !== '' || 
      filters.priceRange.min !== priceRange.min || 
      filters.priceRange.max !== priceRange.max
    );
  }, [filters, priceRange]);

  const getStatusLabel = (statusId: string): string => {
    const labels: Record<string, string> = {
      '0': 'Available for Investment',
      '1': 'Under Inspection',
      '2': 'Pending Approval',
      '3': 'Funding Complete',
      '4': 'Completed',
      '5': 'Cancelled'
    };
    return labels[statusId] || 'Unknown';
  };

  const formatCurrency = (value: number): string => {
    return '$' + value.toLocaleString('en-US');
  };

  const canLoadMore = (): boolean => {
    const totalFiltered = allProperties.filter(({ property }) => {
      // Simplified filter check
      return true;
    }).length;
    return filteredProperties.length < totalFiltered && !isLoading;
  };

  const loadMoreProperties = () => {
    setIsLoadingMore(true);
    setCurrentPage(prev => prev + 1);
    
    setTimeout(() => {
      setIsLoadingMore(false);
    }, 1000);
  };

  const handlePropertyAction = (action: 'view' | 'invest', property: PropertyDetails, address: string) => {
    console.log(`${action} property:`, property, 'at address:', address);
    // Implement navigation or modal opening logic here
  };

  return (
    <Box sx={{ p: 3 }}>
      {/* Header */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          Available Properties
        </Typography>
        <Typography variant="body1" color="text.secondary">
          {filteredProperties.length} of {allProperties.length} properties
        </Typography>
      </Box>

      {/* Filters */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Grid container spacing={2} alignItems="center">
            {/* Search */}
            <Grid item xs={12} md={3}>
              <TextField
                fullWidth
                variant="outlined"
                label="Search properties"
                value={filters.searchTerm}
                onChange={(e) => handleFilterChange('searchTerm', e.target.value)}
                InputProps={{
                  startAdornment: <Search sx={{ color: 'text.secondary', mr: 1 }} />
                }}
                placeholder="Search by ID, seller, or status"
              />
            </Grid>

            {/* Status Filter */}
            <Grid item xs={12} md={2}>
              <FormControl fullWidth>
                <InputLabel>Status</InputLabel>
                <Select
                  value={filters.statusFilter}
                  label="Status"
                  onChange={(e) => handleFilterChange('statusFilter', e.target.value)}
                >
                  <MenuItem value="">All Status</MenuItem>
                  <MenuItem value="0">Available for Investment</MenuItem>
                  <MenuItem value="1">Under Inspection</MenuItem>
                  <MenuItem value="2">Pending Approval</MenuItem>
                  <MenuItem value="3">Funding Complete</MenuItem>
                  <MenuItem value="4">Completed</MenuItem>
                  <MenuItem value="5">Cancelled</MenuItem>
                </Select>
              </FormControl>
            </Grid>

            {/* Sort By */}
            <Grid item xs={12} md={2}>
              <FormControl fullWidth>
                <InputLabel>Sort by</InputLabel>
                <Select
                  value={filters.sortBy}
                  label="Sort by"
                  onChange={(e) => handleFilterChange('sortBy', e.target.value)}
                >
                  <MenuItem value="newest">Newest First</MenuItem>
                  <MenuItem value="price">Price</MenuItem>
                  <MenuItem value="funding">Funding Progress</MenuItem>
                  <MenuItem value="shares">Available Shares</MenuItem>
                </Select>
              </FormControl>
            </Grid>

            {/* Sort Order */}
            <Grid item xs={12} md={2}>
              <FormControl fullWidth>
                <InputLabel>Order</InputLabel>
                <Select
                  value={filters.sortOrder}
                  label="Order"
                  onChange={(e) => handleFilterChange('sortOrder', e.target.value)}
                >
                  <MenuItem value="asc">Ascending</MenuItem>
                  <MenuItem value="desc">Descending</MenuItem>
                </Select>
              </FormControl>
            </Grid>

            {/* Clear Filters */}
            <Grid item xs={12} md={3}>
              <Box sx={{ display: 'flex', gap: 1 }}>
                <Button
                  variant="outlined"
                  onClick={clearFilters}
                  startIcon={<Clear />}
                  disabled={!hasActiveFilters}
                >
                  Clear Filters
                </Button>
                <IconButton onClick={loadProperties} disabled={isLoading}>
                  <Refresh />
                </IconButton>
              </Box>
            </Grid>

            {/* Price Range Slider */}
            <Grid item xs={12}>
              <Typography gutterBottom>
                Price Range: {formatCurrency(filters.priceRange.min)} - {formatCurrency(filters.priceRange.max)}
              </Typography>
              <Slider
                value={[filters.priceRange.min, filters.priceRange.max]}
                onChange={(_, value) => {
                  const [min, max] = value as number[];
                  handleFilterChange('priceRange', { min, max });
                }}
                valueLabelDisplay="auto"
                valueLabelFormat={formatCurrency}
                min={priceRange.min}
                max={priceRange.max}
                step={10000}
                marks={[
                  { value: priceRange.min, label: formatCurrency(priceRange.min) },
                  { value: priceRange.max, label: formatCurrency(priceRange.max) }
                ]}
              />
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {/* Active Filters */}
      {hasActiveFilters && (
        <Box sx={{ mb: 3 }}>
          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
            {filters.searchTerm && (
              <Chip
                label={`Search: ${filters.searchTerm}`}
                onDelete={() => removeFilter('search')}
                color="primary"
                variant="outlined"
              />
            )}
            {filters.statusFilter && (
              <Chip
                label={`Status: ${getStatusLabel(filters.statusFilter)}`}
                onDelete={() => removeFilter('status')}
                color="primary"
                variant="outlined"
              />
            )}
            {(filters.priceRange.min !== priceRange.min || filters.priceRange.max !== priceRange.max) && (
              <Chip
                label={`Price: ${formatCurrency(filters.priceRange.min)} - ${formatCurrency(filters.priceRange.max)}`}
                onDelete={() => removeFilter('price')}
                color="primary"
                variant="outlined"
              />
            )}
          </Box>
        </Box>
      )}

      {/* Loading State */}
      {isLoading && (
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', py: 8 }}>
          <CircularProgress size={60} />
          <Typography variant="h6" sx={{ mt: 2 }}>
            Loading properties...
          </Typography>
        </Box>
      )}

      {/* Empty State */}
      {!isLoading && filteredProperties.length === 0 && allProperties.length === 0 && (
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', py: 8 }}>
          <Home sx={{ fontSize: 80, color: 'text.secondary', mb: 2 }} />
          <Typography variant="h5" gutterBottom>
            No Properties Available
          </Typography>
          <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
            There are currently no properties available for investment.
          </Typography>
          <Button variant="contained" onClick={loadProperties} startIcon={<Refresh />}>
            Refresh
          </Button>
        </Box>
      )}

      {/* No Results State */}
      {!isLoading && filteredProperties.length === 0 && allProperties.length > 0 && (
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', py: 8 }}>
          <SearchOff sx={{ fontSize: 80, color: 'text.secondary', mb: 2 }} />
          <Typography variant="h5" gutterBottom>
            No Properties Found
          </Typography>
          <Typography variant="body1" color="text.secondary" sx={{ mb: 3 }}>
            No properties match your current filters. Try adjusting your search criteria.
          </Typography>
          <Button variant="outlined" onClick={clearFilters} startIcon={<Clear />}>
            Clear All Filters
          </Button>
        </Box>
      )}

      {/* Properties Grid */}
      {!isLoading && filteredProperties.length > 0 && (
        <Grid container spacing={3}>
          {filteredProperties.map(({ property, address }) => (
            <Grid item xs={12} sm={6} md={4} lg={3} key={`${address}-${property.config.nftID}`}>
              <PropertyCard
                property={property}
                escrowAddress={address}
                onViewDetails={(prop, addr) => handlePropertyAction('view', prop, addr)}
                onInvest={(prop, addr) => handlePropertyAction('invest', prop, addr)}
              />
            </Grid>
          ))}
        </Grid>
      )}

      {/* Load More Button */}
      {canLoadMore() && (
        <Box sx={{ display: 'flex', justifyContent: 'center', mt: 4 }}>
          <Button
            variant="contained"
            onClick={loadMoreProperties}
            disabled={isLoadingMore}
            size="large"
          >
            {isLoadingMore ? (
              <>
                <CircularProgress size={20} sx={{ mr: 1 }} />
                Loading...
              </>
            ) : (
              'Load More Properties'
            )}
          </Button>
        </Box>
      )}
    </Box>
  );
}
