// frontend/src/app/components/landing-page/landing-page.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';

@Component({
  selector: 'app-landing-page',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    MatButtonModule,
    MatIconModule,
    MatCardModule
  ],
  template: `
    <div class="landing-container">
      <!-- Hero Section -->
      <section class="hero-section">
        <div class="hero-content">
          <div class="hero-text">
            <h1 class="hero-title">
              Invest in Real Estate
              <span class="gradient-text">Like Never Before</span>
            </h1>
            <p class="hero-subtitle">
              Own fractional shares of premium real estate properties through blockchain technology. 
              Start building your diversified portfolio with as little as $100.
            </p>
            <div class="hero-actions">
              <button mat-raised-button 
                      class="cta-button primary"
                      routerLink="/properties">
              
                Start Investing
              </button>
              <button mat-stroked-button 
                      class="cta-button secondary"
                      routerLink="/portfolio">
  
                View Portfolio
              </button>
            </div>
            <div class="hero-stats">
              <div class="stat-item">
                <div class="stat-number">$2.4M+</div>
                <div class="stat-label">Total Investment</div>
              </div>
              <div class="stat-item">
                <div class="stat-number">150+</div>
                <div class="stat-label">Properties</div>
              </div>
              <div class="stat-item">
                <div class="stat-number">8.2%</div>
                <div class="stat-label">Avg. Annual Return</div>
              </div>
            </div>
          </div>
          <div class="hero-visual">
            <div class="property-cards-showcase">
              <div class="showcase-card card-1">
                <div class="card-image"></div>
                <div class="card-content">
                  <div class="card-title">Luxury Downtown Condo</div>
                  <div class="card-price">$250K • 12.5% APY</div>
                </div>
              </div>
              <div class="showcase-card card-2">
                <div class="card-image"></div>
                <div class="card-content">
                  <div class="card-title">Commercial Office Space</div>
                  <div class="card-price">$500K • 10.8% APY</div>
                </div>
              </div>
              <div class="showcase-card card-3">
                <div class="card-image"></div>
                <div class="card-content">
                  <div class="card-title">Suburban Family Home</div>
                  <div class="card-price">$180K • 9.2% APY</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Features Section -->
      <section class="features-section">
        <div class="features-container">
          <div class="section-header">
            <h2>Why Choose FracEstate?</h2>
            <p>Revolutionary blockchain-powered real estate investment platform</p>
          </div>
          
          <div class="features-grid">
            <div class="feature-card">
              <div class="feature-icon">
                <mat-icon>security</mat-icon>
              </div>
              <h3>Secure & Transparent</h3>
              <p>All transactions are secured on the blockchain with full transparency and immutable records.</p>
            </div>

            <div class="feature-card">
              <div class="feature-icon">
                <mat-icon>account_balance_wallet</mat-icon>
              </div>
              <h3>Low Minimum Investment</h3>
              <p>Start investing in premium real estate with as little as $100. No need for large capital.</p>
            </div>

            <div class="feature-card">
              <div class="feature-icon">
                <mat-icon>trending_up</mat-icon>
              </div>
              <h3>High Yield Returns</h3>
              <p>Earn competitive returns through rental income and property appreciation, paid monthly.</p>
            </div>

            <div class="feature-card">
              <div class="feature-icon">
                <mat-icon>diversity_3</mat-icon>
              </div>
              <h3>Instant Diversification</h3>
              <p>Build a diversified real estate portfolio across different property types and locations.</p>
            </div>

            <div class="feature-card">
              <div class="feature-icon">
                <mat-icon>swap_horiz</mat-icon>
              </div>
              <h3>Liquid Investments</h3>
              <p>Trade your fractional ownership tokens anytime without traditional real estate constraints.</p>
            </div>

            <div class="feature-card">
              <div class="feature-icon">
                <mat-icon>analytics</mat-icon>
              </div>
              <h3>Advanced Analytics</h3>
              <p>Track your portfolio performance with comprehensive analytics and reporting tools.</p>
            </div>
          </div>
        </div>
      </section>

      <!-- How It Works Section -->
      <section class="how-it-works-section">
        <div class="how-it-works-container">
          <div class="section-header">
            <h2>How It Works</h2>
            <p>Start investing in real estate in just a few simple steps</p>
          </div>
          
          <div class="steps-container">
            <div class="step-item">
              <div class="step-number">1</div>
              <div class="step-content">
                <h3>Browse Properties</h3>
                <p>Explore our curated selection of premium real estate properties with detailed information and projections.</p>
                <button mat-stroked-button routerLink="/properties" class="step-action">
                  View Properties
                </button>
              </div>
            </div>

            <div class="step-item">
              <div class="step-number">2</div>
              <div class="step-content">
                <h3>Complete KYC</h3>
                <p>Quick and secure identity verification to comply with regulations and unlock higher investment limits.</p>
                <button mat-stroked-button routerLink="/kyc" class="step-action">
                  Start KYC
                </button>
              </div>
            </div>

            <div class="step-item">
              <div class="step-number">3</div>
              <div class="step-content">
                <h3>Invest & Earn</h3>
                <p>Purchase fractional shares using USDC and start earning monthly yields from rental income.</p>
                <button mat-stroked-button routerLink="/portfolio" class="step-action">
                  View Portfolio
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- CTA Section -->
      <section class="cta-section">
        <div class="cta-container">
          <h2>Ready to Start Building Your Real Estate Portfolio?</h2>
          <p>Join thousands of investors already earning passive income through fractional real estate ownership.</p>
          <div class="cta-actions">
            <button mat-raised-button 
                    class="cta-button primary large"
                    routerLink="/properties">
              Start Investing Today
            </button>
            <button mat-stroked-button 
                    class="cta-button secondary large"
                    routerLink="/dashboard">
              <mat-icon>info</mat-icon>
              Learn More
            </button>
          </div>
        </div>
      </section>
    </div>
  `,
  styleUrls: ['./landing-page.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class LandingPageComponent implements OnInit {

  constructor() { 
    console.log('✅ LandingPageComponent constructor called');
  }

  ngOnInit(): void {
    // Component initialization
    console.log('✅ LandingPageComponent ngOnInit called');
  }
}

// react-frontend/src/components/LandingPage/LandingPage.tsx
import React from 'react';
import {
  Box,
  Typography,
  Button,
  Container,
  Grid,
  Card,
  CardContent,
  CardActions,
  Chip
} from '@mui/material';
import {
  TrendingUp,
  Security,
  AccountBalance,
  Speed,
  Visibility,
  VerifiedUser
} from '@mui/icons-material';
import { useNavigate } from 'react-router-dom';
import { useWallet } from '../../hooks/useWallet';

const features = [
  {
    icon: <TrendingUp sx={{ fontSize: 40 }} />,
    title: 'High Returns',
    description: 'Earn up to 12% APY through real estate tokenization and DeFi yield farming'
  },
  {
    icon: <Security sx={{ fontSize: 40 }} />,
    title: 'Secure Investment',
    description: 'Smart contracts ensure transparent and secure property transactions'
  },
  {
    icon: <AccountBalance sx={{ fontSize: 40 }} />,
    title: 'Fractional Ownership',
    description: 'Invest in premium real estate with as little as $100'
  },
  {
    icon: <Speed sx={{ fontSize: 40 }} />,
    title: 'Instant Liquidity',
    description: 'Trade your property tokens on secondary markets anytime'
  },
  {
    icon: <Visibility sx={{ fontSize: 40 }} />,
    title: 'Full Transparency',
    description: 'All transactions and property data recorded on blockchain'
  },
  {
    icon: <VerifiedUser sx={{ fontSize: 40 }} />,
    title: 'KYC Verified',
    description: 'All properties and investors undergo thorough verification'
  }
];

const stats = [
  { label: 'Total Value Locked', value: '$12.5M' },
  { label: 'Properties Listed', value: '150+' },
  { label: 'Active Investors', value: '2,500+' },
  { label: 'Average APY', value: '8.5%' }
];

export default function LandingPage() {
  const navigate = useNavigate();
  const { isConnected, connectWallet } = useWallet();

  const handleGetStarted = async () => {
    if (!isConnected) {
      try {
        await connectWallet();
      } catch (error) {
        console.error('Failed to connect wallet:', error);
      }
    } else {
      navigate('/properties');
    }
  };

  const handleViewProperties = () => {
    navigate('/properties');
  };

  return (
    <Box sx={{ overflow: 'hidden' }}>
      {/* Hero Section */}
      <Container maxWidth="lg">
        <Box
          sx={{
            py: { xs: 8, md: 12 },
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center'
          }}
        >
          <Typography
            variant="h1"
            sx={{
              fontSize: { xs: '2.5rem', md: '4rem', lg: '5rem' },
              fontWeight: 700,
              mb: 3,
              background: 'linear-gradient(45deg, #00d4ff 30%, #ffffff 90%)',
              backgroundClip: 'text',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent'
            }}
          >
            Fractional Real Estate
          </Typography>
          
          <Typography
            variant="h2"
            sx={{
              fontSize: { xs: '1.5rem', md: '2.5rem' },
              fontWeight: 400,
              mb: 4,
              color: 'text.secondary'
            }}
          >
            Powered by Blockchain
          </Typography>

          <Typography
            variant="h5"
            sx={{
              maxWidth: 600,
              mb: 6,
              color: 'text.secondary',
              lineHeight: 1.6
            }}
          >
            Invest in premium real estate properties through blockchain technology. 
            Own fractions of high-value properties, earn yield, and trade tokens seamlessly.
          </Typography>

          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', justifyContent: 'center' }}>
            <Button
              variant="contained"
              size="large"
              onClick={handleGetStarted}
              sx={{
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                borderRadius: 2
              }}
            >
              {isConnected ? 'Explore Properties' : 'Connect Wallet'}
            </Button>
            
            <Button
              variant="outlined"
              size="large"
              onClick={handleViewProperties}
              sx={{
                px: 4,
                py: 1.5,
                fontSize: '1.1rem',
                borderRadius: 2
              }}
            >
              View Properties
            </Button>
          </Box>
        </Box>
      </Container>

      {/* Stats Section */}
      <Box sx={{ py: 6, backgroundColor: 'rgba(255, 255, 255, 0.02)' }}>
        <Container maxWidth="lg">
          <Grid container spacing={4}>
            {stats.map((stat, index) => (
              <Grid item xs={6} md={3} key={index}>
                <Box sx={{ textAlign: 'center' }}>
                  <Typography
                    variant="h3"
                    sx={{
                      fontWeight: 700,
                      mb: 1,
                      color: 'primary.main'
                    }}
                  >
                    {stat.value}
                  </Typography>
                  <Typography variant="body1" color="text.secondary">
                    {stat.label}
                  </Typography>
                </Box>
              </Grid>
            ))}
          </Grid>
        </Container>
      </Box>

      {/* Features Section */}
      <Container maxWidth="lg">
        <Box sx={{ py: { xs: 8, md: 12 } }}>
          <Typography
            variant="h3"
            sx={{
              textAlign: 'center',
              mb: 2,
              fontWeight: 600
            }}
          >
            Why Choose FracEstate?
          </Typography>
          
          <Typography
            variant="h6"
            sx={{
              textAlign: 'center',
              mb: 8,
              color: 'text.secondary',
              maxWidth: 600,
              mx: 'auto'
            }}
          >
            Experience the future of real estate investment with cutting-edge blockchain technology
          </Typography>

          <Grid container spacing={4}>
            {features.map((feature, index) => (
              <Grid item xs={12} md={6} lg={4} key={index}>
                <Card
                  sx={{
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    p: 2,
                    transition: 'transform 0.3s ease-in-out',
                    '&:hover': {
                      transform: 'translateY(-8px)'
                    }
                  }}
                >
                  <CardContent sx={{ flexGrow: 1, textAlign: 'center' }}>
                    <Box sx={{ color: 'primary.main', mb: 2 }}>
                      {feature.icon}
                    </Box>
                    <Typography variant="h6" gutterBottom>
                      {feature.title}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      {feature.description}
                    </Typography>
                  </CardContent>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Box>
      </Container>

      {/* How It Works Section */}
      <Box sx={{ py: { xs: 8, md: 12 }, backgroundColor: 'rgba(255, 255, 255, 0.02)' }}>
        <Container maxWidth="lg">
          <Typography
            variant="h3"
            sx={{
              textAlign: 'center',
              mb: 8,
              fontWeight: 600
            }}
          >
            How It Works
          </Typography>

          <Grid container spacing={6} alignItems="center">
            <Grid item xs={12} md={4}>
              <Box sx={{ textAlign: 'center' }}>
                <Chip
                  label="1"
                  sx={{
                    width: 60,
                    height: 60,
                    fontSize: '1.5rem',
                    fontWeight: 'bold',
                    mb: 3,
                    backgroundColor: 'primary.main',
                    color: 'black'
                  }}
                />
                <Typography variant="h6" gutterBottom>
                  Connect Your Wallet
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Connect your MetaMask wallet to access the platform and start investing
                </Typography>
              </Box>
            </Grid>

            <Grid item xs={12} md={4}>
              <Box sx={{ textAlign: 'center' }}>
                <Chip
                  label="2"
                  sx={{
                    width: 60,
                    height: 60,
                    fontSize: '1.5rem',
                    fontWeight: 'bold',
                    mb: 3,
                    backgroundColor: 'primary.main',
                    color: 'black'
                  }}
                />
                <Typography variant="h6" gutterBottom>
                  Choose Properties
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Browse verified properties and select the ones that match your investment goals
                </Typography>
              </Box>
            </Grid>

            <Grid item xs={12} md={4}>
              <Box sx={{ textAlign: 'center' }}>
                <Chip
                  label="3"
                  sx={{
                    width: 60,
                    height: 60,
                    fontSize: '1.5rem',
                    fontWeight: 'bold',
                    mb: 3,
                    backgroundColor: 'primary.main',
                    color: 'black'
                  }}
                />
                <Typography variant="h6" gutterBottom>
                  Start Earning
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Receive property tokens and start earning rental income and appreciation
                </Typography>
              </Box>
            </Grid>
          </Grid>
        </Container>
      </Box>

      {/* CTA Section */}
      <Container maxWidth="lg">
        <Box
          sx={{
            py: { xs: 8, md: 12 },
            textAlign: 'center'
          }}
        >
          <Typography
            variant="h3"
            sx={{ mb: 3, fontWeight: 600 }}
          >
            Ready to Start Investing?
          </Typography>
          
          <Typography
            variant="h6"
            sx={{
              mb: 6,
              color: 'text.secondary',
              maxWidth: 500,
              mx: 'auto'
            }}
          >
            Join thousands of investors already earning passive income through fractional real estate
          </Typography>

          <Button
            variant="contained"
            size="large"
            onClick={handleGetStarted}
            sx={{
              px: 6,
              py: 2,
              fontSize: '1.2rem',
              borderRadius: 2
            }}
          >
            {isConnected ? 'Start Investing Now' : 'Connect Wallet to Begin'}
          </Button>
        </Box>
      </Container>
    </Box>
  );
}
